### ISSUE TITLE
Using T3E for different species

### ISSUE THREAD

**Issue by ferygood** [michelleapaz/T3E#7]
Hello Michelle,

Thank you for developing T3E. I'm interested in applying T3E to non-human primates and have encountered some issues.

I have prepared reference and repeat data for chimpanzee (panTro6).
1. When I change the species name from "hg38" to "panTro6" (for chimpanzee) in the first row of `parameters.txt`, `main.sh` fails to execute.
2. I then tried using my chimpanzee reference but kept "hg38" as the species name to bypass the first error. This allowed main.sh to run, but the `probabilities.py` script did not recognize chromosomes like "2A" and "2B":
`Traceback (most recent call last):
  File "/home/t3e/T3E_chimp/scripts/probabilities.py", line 82, in <module>
    freq_reads= read_frequency()
  File "/home/t3e/T3E_chimp/scripts/probabilities.py", line 43, in read_frequency
    chr_reads[chrom].append(read)
KeyError: 'chr2A'
`

Is it possible to adapt T3E to work with species other than human and mouse?
Thank you very much!

**Comment by michelleapaz** [comment]
Hello, 

Thanks for you interest in using T3E!

Although T3E was designed and tested for human and mouse ChIP-seq data, in principle it can be modified accordingly to handle any other species. 

It is important to note that you need to provide the TE annotation file for the species of interest (e.g., chimpanzee) in the format described in the documentation. A few modifications are necessary:

1)	In the _main.sh_ script (L62), you should add the species of interest (e.g., panTro6): 

`if [[ ! $SPECIES =~ ^(hg38|mm10|panTro6)$ ]]; then`

2)	In the _probabilities.py_ (L66) and _t3e.py_ (L220) scripts, you should add the chromosomes of your species of interest according to the assembly you used to map. Example:
```
if (species == "hg19" or species == "hg38"):
	chromosomes = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]
elif (species == "mm10"):
	chromosomes = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chrX", "chrY"]
elif (species == "panTro6"):
	chromosomes = ["chr1", "chr2A", "chr2B","chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]
else:
	sys.exit("[ERROR] Species not defined correctly!")
```

You could try using a few iterations to test the code. If there are any other issues adapting the original code for your own purposes, do not hesitate to contact me.

Cheers,

Michelle

**Comment by ferygood** [comment]
Hello Michelle,

Thank you for your quick response and helpful suggestions. I would like to confirm that making these two modifications in the script enables T3E to run on other species. Over the past week, I tested it on chimpanzee data by including chr2A and chr2B, and it worked well.

Thank you again for your support!

**Comment by ferygood** [comment]
Hi Michelle, 

I encounter another issue after testing it on orangutan samples. I added chr2a, chr2b, and chrUn following the suggestions you provided.

However, there is an error in line 90 in probabilities.py:

`Traceback (most recent call last):
  File "./T3E_oran/scripts/probabilities.py", line 90, in <module>
    first_pos = int(list(pos_prob.keys())[0])
IndexError: list index out of range
`
I have added the full log file below which I use 1 iteration to test the pipeline.
[log.txt](https://github.com/user-attachments/files/18020627/log.txt)

Could you provide me some guides on some possible solutions for it? 
If you need additional information of the analysis, please let me know.



Thank you for your time again!

**Comment by michelleapaz** [comment]
Hi,

I apologise for the late response. I actually saw that it worked for chimpanzee data and missed the issue you encountered later on for orangutan. 

If you still have this issue, please provide the modifications you included in the code for orangutan as well. 

According to the log.txt you included previously, the probabilities were calculated for the 24 different chromosomes. However, the script is trying to access an index that does not exist in the list you provided.

Best,

Michelle
